// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzeomaxcafiqwxlskwvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZW9tYXhjYWZpcXd4bHNrd3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDQ0MzEsImV4cCI6MjA3MDQ4MDQzMX0.OUzozhmsXeXu5_nd4_wUaVVjVqDiJVW_vGNwpEsCrII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});